courses_data = """[
  {
    "id": 1,
    "created_at": "2023-08-25 06:36:35",
    "updated_at": "2024-09-24 03:04:29",
    "title": "Learn JavaScript the Hard Way",
    "description": "An exercise based logical course in the most popular language in the world.",
    "price": 59,
    "active": 1,
    "media_id": null,
    "slug": "learn-javascript-the-hard-way",
    "short_blurb": "An exercise based logical course in the most popular language in the world.",
    "docs_url": "/products/learn-javascript-the-hard-way.html",
    "poster": "/covers/learn-js-the-hard-way.jpg",
    "category": "JavaScript",
    "created_by": "Zed A. Shaw",
    "preorder": 1,
    "bundle_parent": "epic-supporter-package",
    "is_bundle": 0,
    "upgrade_product_id": null,
    "external_links": null,
    "bundle": [ ]
  },
  {
    "id": 2,
    "created_at": "2017-04-25T15:47:11.618Z",
    "updated_at": "2024-09-24 03:04:29",
    "title": "Learn Python 3 the Hard Way",
    "description": "The Python 3 Edition of Learn Python the Hard Way",
    "price": 0,
    "active": 0,
    "media_id": null,
    "slug": "learn-python-3-the-hard-way",
    "short_blurb": "The Python 3 Edition of Learn Python the Hard Way",
    "docs_url": "/products/learn-python-3-the-hard-way.html",
    "poster": "/covers/learn-python-3-the-hard-way.jpg",
    "category": "Python",
    "created_by": "Zed A. Shaw",
    "preorder": 0,
    "bundle_parent": "learn-python-the-hard-way-5e-2023",
    "is_bundle": 0,
    "upgrade_product_id": 3,
    "external_links": null,
    "bundle": [ ]
  }
]
"""


course_data = """
{
  "id": 1,
  "created_at": "2023-08-25 06:36:35",
  "updated_at": "2024-09-24 03:04:29",
  "title": "Learn JavaScript the Hard Way",
  "description": "An exercise based logical course in the most popular language in the world.",
  "price": 59,
  "active": 1,
  "media_id": null,
  "slug": "learn-javascript-the-hard-way",
  "short_blurb": "An exercise based logical course in the most popular language in the world.",
  "docs_url": "/products/learn-javascript-the-hard-way.html",
  "poster": "/covers/learn-js-the-hard-way.jpg",
  "category": "JavaScript",
  "created_by": "Zed A. Shaw",
  "preorder": 1,
  "bundle_parent": "epic-supporter-package",
  "is_bundle": 0,
  "upgrade_product_id": null,
  "external_links": null,
  "modules": [
    {
      "id": 8,
      "created_at": "2022-02-09 22:53:32",
      "updated_at": "2024-09-24 03:04:29",
      "title": "First Steps",
      "description": "Installing required software and advice for beginners.",
      "subject": "setup",
      "poster": null,
      "is_free": 0,
      "ordering": 0,
      "build_source": "/modules/ljsthw-first-steps/",
      "published": 1,
      "slug": "ljsthw-first-steps",
      "state": "final",
      "product_id": 1,
      "product_slug": "learn-javascript-the-hard-way",
      "title_slug": "0-first-steps"
    },
    {
      "id": 9,
      "created_at": "2022-01-15 19:23:10",
      "updated_at": "2024-09-24 03:04:29",
      "title": "JavaScript Level 1",
      "description": "Introduction to all of the basic elements of JavaScript.",
      "subject": "javascript",
      "poster": null,
      "is_free": 1,
      "ordering": 3,
      "build_source": "/modules/ljsthw-javascript-level-1/",
      "published": 1,
      "slug": "ljsthw-javascript-level-1",
      "state": "final",
      "product_id": 1,
      "product_slug": "learn-javascript-the-hard-way",
      "title_slug": "3-javascript-level-1"
    },
    {
      "id": 10,
      "created_at": "2022-05-05 20:02:32",
      "updated_at": "2024-09-24 03:04:29",
      "title": "JavaScript Level 2",
      "description": "A set of 10 small projects that refine and practice your JavaScript skills.",
      "subject": "javascript",
      "poster": null,
      "is_free": 0,
      "ordering": 4,
      "build_source": "/modules/ljsthw-javascript-level-2/",
      "published": 1,
      "slug": "ljsthw-javascript-level-2",
      "state": "draft",
      "product_id": 1,
      "product_slug": "learn-javascript-the-hard-way",
      "title_slug": "4-javascript-level-2"
    },
    {
      "id": 58,
      "created_at": "2022-01-16 02:01:48",
      "updated_at": "2024-09-24 03:04:29",
      "title": "CSS Basics",
      "description": "Learn a simple way to use CSS to style HTML.",
      "subject": "css",
      "poster": null,
      "is_free": 0,
      "ordering": 2,
      "build_source": "/modules/ljsthw-css-basics/",
      "published": 1,
      "slug": "ljsthw-css-basics",
      "state": "final",
      "product_id": 1,
      "product_slug": "learn-javascript-the-hard-way",
      "title_slug": "2-css-basics"
    },
    {
      "id": 60,
      "created_at": "2022-01-16 01:35:56",
      "updated_at": "2024-09-24 03:04:29",
      "title": "HTML Basics",
      "description": "Learn how browsers structure the content you see using HTML tags.",
      "subject": "html",
      "poster": null,
      "is_free": 0,
      "ordering": 1,
      "build_source": "/modules/ljsthw-html-basics/",
      "published": 1,
      "slug": "ljsthw-html-basics",
      "state": "final",
      "product_id": 1,
      "product_slug": "learn-javascript-the-hard-way",
      "title_slug": "1-html-basics"
    }
  ],
  "bundle": [ ]
  }
"""
